spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=fitness_activity_db
server.port=8081
logging.level.org.springframework.data.mongodb=DEBUG
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
rabbitmq.exchange.name=fitness.exchange
rabbitmq.queue.name=activity.queue
rabbitmq.routing.key=activity.tracking
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest