eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
server.port=8082
spring.data.mongodb.uri=mongodb+srv://nodejsboy:nodejsboy@cluster0.rrq3auj.mongodb.net/fitnessrecommendations
spring.data.mongodb.database=fitnessrecommendations
rabbitmq.exchange.name=fitness.exchange
rabbitmq.queue.name=activity.queue
rabbitmq.routing.key=activity.tracking
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=
gemini.api.key=AIzaSyDGy1B6hiLCry1ADVn1tBgsV0Cbvyv1ZbI